### ISSUE TITLE
[DynamicDelivery] Mix Kotlin and Java in the same slide "Base module SplitInstallManager"

### ISSUE THREAD

**Issue by bowserf** [Mercandj/presentation#25]
In MD file, we define the language, but it's not visible when we look to the presentation. We should avoid to mix 2 languages.

I know `SplitInstallManager` is written in Java and that you want to write your samples in Kotlin but it's not very friendly I think.

At least, indicate used languages under.

**Comment by Mercandj** [comment]
Yep I thought of that when writing that. Convert to Kotlin seems the way to go

**Comment by bowserf** [comment]
Fixed
